-- PART 1
WITH MY_POPULATION AS (
SELECT P.ID, 1 Input1, CAST(2 AS INT) Input2
FROM(
    SELECT A.ID, X.VALUE, ROW_NUMBER() OVER (PARTITION BY A.ID ORDER BY A.ID) RN
    FROM NEXUS_DW.dbo.AdventofCodeDay02 A
    CROSS APPLY STRING_SPLIT(A.MY_INPUT, ' ') X
    ) A
PIVOT (MAX(A.VALUE) FOR A.RN IN (1,2)) P
)
SELECT SUM(CASE WHEN Input1 = 'forward' THEN Input2 ELSE 0 END)
     * SUM(CASE WHEN Input1 = 'down'    THEN Input2
                WHEN Input1 = 'up'      THEN Input2 * -1 ELSE 0 END) Product
  FROM MY_POPULATION
;

-- PART 2
DECLARE @H INT = 0;
DECLARE @A INT = 0;
DECLARE @D BIGINT = 0;
DECLARE @I0 INT;
DECLARE @I1 VARCHAR(100);
DECLARE @I2 INT;

DECLARE MY_CUR CURSOR FOR
WITH MY_POPULATION AS (
SELECT P.ID, [1] Input1, CAST([2] AS INT) Input2
FROM(
    SELECT A.ID, X.VALUE, ROW_NUMBER() OVER (PARTITION BY A.ID ORDER BY A.ID) RN
    FROM NEXUS_DW.dbo.AdventofCodeDay02 A
    CROSS APPLY STRING_SPLIT(A.MY_INPUT, ' ') X
    ) A
PIVOT (MAX(A.[VALUE]) FOR A.RN IN ([1],[2])) P
)
SELECT *
  FROM MY_POPULATION
ORDER BY ID;

OPEN MY_CUR;
FETCH NEXT FROM MY_CUR INTO @I0, @I1, @I2;
WHILE @@FETCH_STATUS = 0
    BEGIN
        IF @I1 = 'forward' SET @H = @H + @I2;
        IF @I1 = 'down'    SET @A = @A + @I2;
        IF @I1 = 'up'      SET @A = @A - @I2;
        IF @I1 = 'forward' SET @D = @D + @I2 * @A;
    PRINT 'ID: ' + CAST(@I0 AS VARCHAR) + ' NAME: ' + CAST(@I1 AS VARCHAR) + ' VALUE: ' + CAST(@I2 AS VARCHAR) + ' H: ' + CAST(@H AS VARCHAR) + ' A: ' + CAST(@A AS VARCHAR) +  + ' D: ' + CAST(@D AS VARCHAR);
    FETCH NEXT FROM MY_CUR INTO @I0, @I1, @I2;
    END;

PRINT @H * @D;
CLOSE MY_CUR;
DEALLOCATE MY_CUR;