-- PART 1
WITH MY_TEST AS (
SELECT ID
      ,MY_NUMBER
      ,LEAD(MY_NUMBER,1,0) OVER (ORDER BY ID) NEXT_NUMBER
  FROM NEXUS_DW.dbo.AdventofCodeDay01
)
SELECT SUM(CASE WHEN NEXT_NUMBER > MY_NUMBER THEN 1 ELSE 0 END) IncreasingCount
FROM MY_TEST
;
-- PART 2
WITH MY_POPULATION AS (
SELECT ID
      ,MY_NUMBER NUMBER1
      ,LEAD(MY_NUMBER,1,0) OVER (ORDER BY ID) NUMBER2
      ,LEAD(MY_NUMBER,2,0) OVER (ORDER BY ID) NUMBER3
  FROM NEXUS_DW.dbo.AdventofCodeDay01
), MY_TEST AS (
SELECT ID
      ,NUMBER1+NUMBER2+NUMBER3 MY_NUMBER
      ,LEAD(NUMBER1+NUMBER2+NUMBER3,1,0) OVER (ORDER BY ID) NEXT_NUMBER
  FROM MY_POPULATION
)
SELECT SUM(CASE WHEN NEXT_NUMBER > MY_NUMBER THEN 1 ELSE 0 END) IncreasingCount
FROM MY_TEST
;
-- TESTING
WITH MY_DEMO AS (
SELECT 1 ID, 199  MY_NUMBER      UNION ALL
SELECT 2 ID, 200  MY_NUMBER      UNION ALL
SELECT 3 ID, 208  MY_NUMBER      UNION ALL
SELECT 4 ID, 210  MY_NUMBER      UNION ALL
SELECT 5 ID, 200  MY_NUMBER      UNION ALL
SELECT 6 ID, 207  MY_NUMBER      UNION ALL
SELECT 7 ID, 240  MY_NUMBER      UNION ALL
SELECT 8 ID, 269  MY_NUMBER      UNION ALL
SELECT 9 ID, 260  MY_NUMBER      UNION ALL
SELECT 10 ID, 263  MY_NUMBER
), MY_POPULATION AS (
SELECT ID
      ,MY_NUMBER NUMBER1
      ,LEAD(MY_NUMBER,1,0) OVER (ORDER BY ID) NUMBER2
      ,LEAD(MY_NUMBER,2,0) OVER (ORDER BY ID) NUMBER3
  FROM MY_DEMO
), MY_TEST AS (
SELECT ID
      ,NUMBER1+NUMBER2+NUMBER3 MY_NUMBER
      ,LEAD(NUMBER1+NUMBER2+NUMBER3,1,0) OVER (ORDER BY ID) NEXT_NUMBER
  FROM MY_POPULATION
)
SELECT SUM(CASE WHEN NEXT_NUMBER > MY_NUMBER THEN 1 ELSE 0 END) IncreasingCount
FROM MY_TEST
;
